### ISSUE TITLE
Missing Missions/Spacecraft from target page

### ISSUE THREAD

**Issue by jordanpadams** [sbn-psi/archive-viewer#1]
InSight mission is missing from the Mars target page:

https://sbnarchivedemo.psi.edu/?target=urn:nasa:pds:context:target:planet.mars

I imagine this is because it hasn't been explicitly tagged in the archive-loader? Instead of requiring a tag in the archive-loader, could it fallback to the registry for the rest?

**Comment by mdrum** [comment]
All displayed relationships are based on the registry, with only a couple exceptions: Target-to-target relationships are all added by hand in archive-loader, and certain mission-spacecraft relationships are overridden in case they are many-to-many so that they appear one-to-one.

In this case, the issue is just with the context object itself: [The Spacecraft object has no reference to Mars](https://starbase.jpl.nasa.gov/pds4/context-pds4/instrument_host/spacecraft.insight_1.0.xml). Once that gets updated, archive-viewer should automatically pick it up.

We're tracking issues like this in [this google doc](https://docs.google.com/spreadsheets/d/1zsztn7hY71rCv01VlpPiWBAy-zvD4wpDp9hrrDaz5PY/edit?usp=sharing)
